version: '{build}'
init:
  - 'git config --global core.autocrlf true'
branches:
  except:
    - gh-pages
    - l10n_develop
skip_commits:
  files:
    - '*.md'
    - LICENSE
    - .travis.yml
environment:
  matrix:
    - nodejs_version: 10
    - nodejs_version: 8
    - nodejs_version: 9
    - nodejs_version: 11
platform:
  - x64
install:
  - ps: 'Install-Product node $env:nodejs_version $env:platform'
  - 'node --version && npm --version'
  - 'if exist node_modules rd /Q /S node_modules'
  - 'if exist frontend\node_modules rd /Q /S frontend\node_modules'
  - 'npm install --production'
  - 'npm run package'
build: off
test: off
matrix:
  fast_finish: true
artifacts:
  -
    path: 'dist\*'
deploy:
  -
    provider: GitHub
    draft: true
    auth_token:
      secure: bFkucwU1Zoh4EgzKmTAwONzQxuWPWrPGa+yXgadKQRd2jz5JPDZEw1f1vz2r+7i1
    on:
      appveyor_repo_tag: true
notifications:
  -
    provider: Slack
    incoming_webhook:
      secure: KzO8e88B0LKqAI0BQM6lNhCIn9rxAava3AcdVJDyTw420OLIAlK+qzzbLXaR0jSH9zIJz9zu0iGS1iaqu9Co+6owYUrHJlBGrUZ/lZNCsDo=
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: true
