include:
  - template: Auto-DevOps.gitlab-ci.yml

variables:
  SAST_EXCLUDED_PATHS: "frontend/src/assets/private/**"
  TEST_DISABLED: "true"
  DAST_DISABLED: "true"
  GITLAB_TOKEN: glpat-XXXXXXXXXXXXXXXXXpjR
  #bogus GitLab PAT

