version: '{build}'
init:
  - git config --global core.autocrlf true
branches:
  except:
  - gh-pages
  - lightning-talk
environment:
  matrix:
    - nodejs_version: 4 # recommended version
    - nodejs_version: 5
    - nodejs_version: 6
platform:
  - x64
install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - node --version && npm --version
  - if exist node_modules rd /Q /S node_modules # workaround for npm install bug missing module dependencies
  - npm install
  - node_modules\.bin\grunt package
build: off
test: off
matrix:
  fast_finish: true
artifacts:
  - path: dist\*
deploy:
  - provider: GitHub
    draft: true
    auth_token:
      secure: bFkucwU1Zoh4EgzKmTAwONzQxuWPWrPGa+yXgadKQRd2jz5JPDZEw1f1vz2r+7i1
    on:
      appveyor_repo_tag: true
notifications:
  - provider: Webhook
    url:
      secure: c4xwvfA2YpTyASkpasFt2vA6q4pCxCMoWhfX9/JwBxp6rub4dphj6smGxy+5rnsHcvVU6/FvzVHQo4hoxL5gOA==
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true