---
application:
  domain: "sick-sh.op"
  name: "Sick-Shop"
  logo: "https://openclipart.org/image/300px/svg_to_png/250927/1465228117.png"
  numberOfRandomFakeUsers: 50
  showChallengeSolvedNotifications: false
  theme: "cosmo"
  gitHubRibbon: "green"
  twitterUrl: ~
  facebookUrl: ~
  recyclePage:
    topProductImage: "david-benjamin-Hammer.png"
    bottomProductImage: "Headache.png"
  altcoinName: Illcoin
  cookieConsent:
    backgroundColor: '#106326'
    textColor: '#ffffff'
    buttonColor: '#ffffff'
    buttonTextColor: '#000000'
    message: 'This website uses medic...cookies to ensure you get the healthiest tracking experience.'
    dismissText: 'Cough! Cough!'
    linkText: 'But I don`t feel sick!'
    linkUrl: 'http://www.cookinglight.com/food/recipe-finder/healthy-cookies'
products:
  - name: "Cold"
    price: 10
    description: "Small cold to stay in bed some days"
    image: "https://openclipart.org/image/300px/svg_to_png/100351/cold.png"
    reviews:
      - text: 'One of my least favorite!'
        author: 'admin'
  - name: "Bad cold"
    price: 150
    description: "Bad cold gives you everything you need to stay around a week in bed."
    image: "https://openclipart.org/image/300px/svg_to_png/100351/cold.png"
  - name: "Torn Meniscus"
    price: 1150
    description: "Don't want to go every day to your office for the next month? Take a torn meniscus!"
    image: 'Wooden-crutch.jpg'     # Exif metadata contains link to a Thingiverse thing as subtle hint...
    fileForRetrieveBlueprintChallenge: 'crutch.123dx' # ...to this filename as one of its (few) downloads
  - name: "Little headache"
    price: 15
    description: "Feel like smoothly rubbing sandpaper on your brain."
    image: "https://openclipart.org/image/300px/svg_to_png/273493/Headache.png"
    urlForProductTamperingChallenge: 'https://en.wikipedia.org/wiki/Headache'
  - name: "Headache"
    price: 15
    description: "Feel like smashing a hammer in your brain."
    image: "https://openclipart.org/image/300px/svg_to_png/4793/david-benjamin-Hammer.png"
  - name: "Brain fog"
    price: 150
    description: "Expand your skills, forget what you are doing while you are actually doing it!"
    image: "https://openclipart.org/image/300px/svg_to_png/181757/elephantforget.png"
  - name: "Diarrhea"
    price: 150
    description: "Get rid of work with diarrhea"
    image: "https://openclipart.org/image/300px/svg_to_png/172910/intestinal-party.png"
    reviews:
      - text: 'Those puny humans are so embarrassing...'
        author: 'bender'
  - name: "Fiber"
    price: 20
    description: "Fiber at your door step"
    image: "https://openclipart.org/image/300px/svg_to_png/46393/THERMO01.png"
  - name: "Sunburn"
    price: 150
    description: "Feel like on holiday"
    image: "https://openclipart.org/image/300px/svg_to_png/195913/sunburn-woman.png"
    reviews:
      - text: 'This is what you get from taking off your shirt all the time!'
        author: 'jim'
  - name: "Heart attack"
    price: 5000
    description: "Have a lightning in your heart"
    image: "https://openclipart.org/image/300px/svg_to_png/154747/herzinfarkt.png"
    useForChristmasSpecialChallenge: true
