version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    target_branch: "develop"
    default_reviewers:
      - "bkimminich"
    default_labels:
      - "dependencies"
    ignored_updates:
      - match:
          dependency_name: "express-jwt"
          version_requirement: "0.1.3"
      - match:
          dependency_name: "sanitize-html"
          version_requirement: "1.4.2"
      - match:
          dependency_name: "unzipper"
          version_requirement: "0.9.15"
  - package_manager: "javascript"
    directory: "/frontend"
    update_schedule: "live"
    target_branch: "develop"
    default_reviewers:
      - "bkimminich"
    default_labels:
      - "dependencies"
