name: SonarQubeAudit
on:
  push:
    branches:
      - master
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Importante para el an치lisis de Churn

      - name: Install Dependencies
        run: npm install --legacy-peer-deps #--ignore-scripts # Instalaci칩n r치pida

      - name: Run All Tests (Frontend & Backend)
        run: |
          export CHROME_BIN=/usr/bin/google-chrome
          cd frontend && npm run test -- --watch=false --code-coverage --browsers=ChromeHeadless && cd ..
          npm run test:server || echo "Algunos tests fallaron, continuando con el an치lisis..."

      - name: Debug - List all lcov files
        run: |
          echo "Buscando archivos de cobertura generados..."
          find . -name "lcov.info"

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=dacaslles_juice-shop
            -Dsonar.organization=dacaslles
            -Dsonar.sources=app.ts,server.ts,lib,models,routes,frontend/src
            -Dsonar.tests=test,frontend/src
            -Dsonar.test.inclusions=test/**,frontend/src/**/*.spec.ts,frontend/src/**/*.test.ts
            -Dsonar.exclusions=data/**,**/node_modules/**,**/dist/**,**/*.json,cypress/**
            -Dsonar.javascript.lcov.reportPaths=build/reports/coverage/frontend-tests/lcov.info,build/reports/coverage/server-tests/lcov.info