name: Pipeline scan and Issue importer

on: push
#on: gollum          # sort of a dummy to prevent this from running

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2          
      - name: GitHub Action for Bash
        uses: lafernando/github-action-bash@v1.0
      - uses: cycodelabs/cimon-action@v0
        with:
          client-id: ${{ secrets.CIMON_CLIENT_ID }}
          secret: ${{ secrets.CIMON_SECRET }}
       # script: 
      - run: curl -sfL https://raw.githubusercontent.com/Bearer/bearer/main/contrib/install.sh | sh
      - run: ./bin/bearer scan ./* --output=./theresults.json --format=json
      - run: ls -lahrt && pwd
          
      - name: save archive
        uses: actions/upload-artifact@v2
        with:
          name: theresults.json
          path: .
      - name: get archive
        uses: actions/download-artifact@v2
        with:
          name: theresults.json
          path: .

      
      - uses: khorwood/sarif-converter@main
        with:
          type: checkov
          input: ./theresults.json
          output: ./theresults.sarif
