name: OWASP ZAP DAST pipeline

on:
  push:
    branches:
      - feature/truong

jobs:
  zap-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      
      - name: Check target availability
        run: |
          echo " Checking if http://localhost:3000 is reachable..."
          curl -I http://localhost:3000 || echo " App not reachable yet"

      
      - name: Run OWASP ZAP DAST Scan
        uses: zaproxy/action-baseline@v0.9.0
        with:
          target: 'http://localhost:3000'
          cmd_options: '-a' 
