name: DAST Scan (OWASP ZAP)

on:
  push:
    branches:
      - feature/truong   
  workflow_dispatch:     
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Run OWASP ZAP DAST Scan

    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v4

     
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3


      
      - name: Run OWASP ZAP baseline scan
        run: |
          docker run -v $(pwd):/zap/wrk/:rw \
            owasp/zap2docker-stable zap-baseline.py \
            -t https://8999cd7bbecf.ngrok-free.app \
            -r zap-report.html || true

      
      - name: Upload ZAP Scan Report
        uses: actions/upload-artifact@v4
        with:
          name: ZAP-DAST-Report
          path: zap-report.html
