name: OWASP ZAP DAST pipeline

on:
  push:
    branches:
      - feature/truong

jobs:
  zap-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start Juice Shop container
        run: |
          docker run -d -p 3000:3000 bkimminich/juice-shop
          sleep 30  # đợi app khởi động hoàn tất

      - name: Run OWASP ZAP baseline scan
        uses: zaproxy/action-baseline@v0.9.0
        with:
          target: 'http://localhost:3000'
          cmd_options: '-a'
