name: "Spam PR processing"
on:
  pull_request:
    types:
      - labeled
permissions:
  pull-requests: write
jobs:
  add-comment:
    if: github.event.label.name == 'spam'
    runs-on: ubuntu-latest
    steps:
      - name: Add spam comment
        run: gh pr comment "$NUMBER" --body "$BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.pull_request.number }}
          BODY: >
            Hi ðŸ‘‹,
            
            This pull request has been marked as spam.
            
            This usually means that the pull request contains experiments that are not relevant to Juice Shop.
            While it's great to see that Juice Shop is useful for experiments and learning experiences, we receive a high volume of such PRs, making it increasingly difficult to manage.
            
            All maintainers who have subscribed to the repository must manually review and dismiss these PRs, which requires significant effort and reduces the time we can dedicate to improving the project.
            
            Additionally, your account has been temporarily blocked from the Juice Shop GitHub organization to prevent accidental submission of similar PRs in the future.
            What can you do now?
            
            If you believe this was a mistake, please reach out via the OWASP Slack channel #juice-shop. You can find community links here: OWASP Juice Shop Community.
            If you submitted this PR while following a tutorial, blog post, corporate/university training, or similar resource, please inform the trainers or content creators and ask them to update their materials to avoid using Juice Shop for this purpose.
            We appreciate your understanding and hope you will continue to contribute meaningfully to the Juice Shop project.
            
            Sincerely,
            The Juice Shop Maintainers ðŸ§ƒ
