name: 'Close stale issues and PR'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@5ebf00ea0e4c1561e9b43a292ed34424fb1d4578 #v6.0.1 TODO Upgrade to v8.0.0 or later
        with:
          stale-issue-message: >
            This issue has been automatically marked as `stale` because it has not had
            recent activity. :calendar: It will be _closed automatically_ in one week if no further activity occurs.
          stale-pr-message: >
            This PR has been automatically marked as `stale` because it has not had
            recent activity. :calendar: It will be _closed automatically_ in two weeks if no further activity occurs.
          close-issue-message: This issue was closed because it has been stalled for 7 days with no activity.
          close-pr-message: This PR was closed because it has been stalled for 14 days with no activity.
          days-before-stale: 14
          days-before-close: 7
          days-before-pr-close: 14
          exempt-issue-labels: 'critical,technical debt'
          exempt-assignees: bkimminich
