name: 'Close stale issues and PR'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4
        with:
          stale-issue-message: >
            This issue has been automatically marked as `stale` because it has not had
            recent activity. :calendar: It will be _closed automatically_ in one week if no further activity occurs.
          stale-pr-message: >
            This PR has been automatically marked as `stale` because it has not had
            recent activity. :calendar:
          close-issue-message: This issue was closed because it has been stalled for 7 days with no activity.
          days-before-stale: 14
          days-before-close: 7
          days-before-pr-close: -1
          exempt-issue-labels: 'critical,technical debt'