on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web_application
    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#       with:
#         ref: master
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.13.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://fictional-space-tribble-45q59ggvqvgcww4-3000.app.github.dev/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
