name: "ZAP Baseline Scan"

on:
  schedule:
    - cron:  '0 18 * * 6'

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan Juice Shop preview instance on Heroku
    steps:
      - name: Check out Git repository
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f #v2: v2.3.4 available
        with:
          ref: develop
      - name: ZAP Scan
        uses: zaproxy/action-baseline@41aee98ebc7cf2802c3beae4e7d4336413a21e43 # v0.9.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'https://preview.owasp-juice.shop'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a -j'
